from .aixdzs import AixdzcNovelParser
from .base import BaseNovelParser
from .downloader import Downloader
from .hzpxw import HzpxwNovelParser
from .lanlanguoji import LanlanNovelParser
from .quanben import QuanBenNovelParser
from .trxs import TrxsNovelParser
from .wushuang import WuShuangNovelParser
from .xiashuyun import XiaShuYunNovelParser
